feat: add friend schedule tab
manyaak/manyaak-front pull request #26
Opened 2023-08-12 07:43 UTC by ballsona

## 🔗 Issue Number
#25 
## 📄 Description
친구의 일정을 볼 수 있는 상세 페이지 UI 구현을 완료했어요
## ✅ Checklist

- [X] PR 제목을 commit 규칙에 맞게 작성했나요?
- [X] label을 설정했나요?
- [X] 작업한 사람 모두를 Assign 했나요?
- [X] Code Review를 요청 했나요?

2023-08-16 16:26 UTC, aube-dev requested changes
LGTM 👍 이지만 하나만 확인해 주세요!

2023-08-16 16:26 UTC, aube-dev commented on src/components/friend/schedule/FriendScheduleContent/FriendScheduleContent.tsx
> +  };
순수하게 궁금한 부분인데, 혹시 이걸 1 depth에서 바로 받지 않고 `userProfileInfo` 안에 nesting해서 받는 이유가 있을까요?

2023-08-16 16:26 UTC, aube-dev commented on src/components/friend/schedule/FriendScheduleContent/ScheduleList/ScheduleList.tsx
> +const today = new Date();
🍋 컴포넌트 바깥에서 `new Date()`를 하면 이 스크립트가 최초 실행되는 시점에 `today`가 결정되고 다시는 바뀌지 않아서 위험할 것 같아요!

2023-08-16 23:47 UTC, kanghyun98 commented on src/components/friend/schedule/FriendScheduleContent/FriendScheduleContent.tsx
> +  };
제 추측인데, 추후에 다른 props가 추가되었을때 유저 프로필 데이터는 그룹화시키려는 목적인 것 같아요..? 만약 이게 맞다면 저는 이 방식에 어느정도 동의하는 바 입니다!

2023-08-16 23:56 UTC, kanghyun98 approved these changes
LGTM👍👍 고생 많았슴다

2023-08-16 23:56 UTC, kanghyun98 commented on src/components/friend/schedule/FriendScheduleContent/FriendScheduleContent.tsx
> +        친구 연결 끊기
이거 보니 생각난건데, 이런 버튼 텍스트 같은 것들을 상수화해서 관리하는건 어떨까요? 저도 생각만하고 적용 안한건데, 여러분들 의견이 궁금합니다! @aube-dev @ballsona

2023-08-23 09:59 UTC, ballsona commented on src/components/friend/schedule/FriendScheduleContent/FriendScheduleContent.tsx
> +  };
@aube-dev  강현님이 말씀해주신게 정확합니다 ..! 지금은 친구 일정 데이터가 dummyData로 들어가있어서 props에 생략 되어있지만, 일정 <-> 프로필 관련 데이터가 한번 그룹화되어 props로 받아오는게 더 깔끔할 것 같다구 생각했어요..!

2023-08-23 10:00 UTC, ballsona commented on src/components/friend/schedule/FriendScheduleContent/FriendScheduleContent.tsx
> +        친구 연결 끊기
좋아요! 음 만약에 group -> club 작업 한다고 하면, 그 브랜치에서 이부분도 같이 작업해도 괜찮을듯 ..! 합니다

2023-08-23 10:02 UTC, ballsona commented on src/components/friend/schedule/FriendScheduleContent/ScheduleList/ScheduleList.tsx
> +const today = new Date();
악 그런 위험성이 있군요 당장 수정할게요 감사합니다 !!

2023-08-23 14:57 UTC, aube-dev approved these changes

2023-08-23 19:39 UTC, merged